import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./(Components)/Navbar";
import { Inter, Roboto, Poppins } from "next/font/google";
import { ThemeProvider } from "./(Components)/ThemeProvider";
import { Toaster } from "react-hot-toast";
import Footer from "./(Components)/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const Robotos = Roboto({
  weight: ["100", "300", "400", "500", "700", "900"],
  subsets: ["latin"],
  variable: "--font-roboto",
});

export const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-inter",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${Robotos.variable} box-border antialiased font-mono`}>
        <div className="min-h-screen">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <section className="max-w-6xl mx-auto w-full p-2">
              {children}
              <Toaster
                position="top-right"
                toastOptions={{
                  duration: 5000,
                }}
              />
            </section>
              <Footer />
          </ThemeProvider>
        </div>
      </body>
    </html>
  );
}
